config/routes.rb
NewNettiaika::Application.routes.draw do
  #faye_server '/faye', timeout: 25
  #get '/chat', to: RealtimeChatController

  namespace :admin do
    resources :users, :settings, :footer_pages, :contacts, :languages, :email_templates, :companies, :company_admins, :payment_types
    get '/company/languages' => 'companies#language_list'
    get '/company/languages' => 'companies#language_list' , as: :language_list
    get '/company/:id/edit_language' => 'companies#edit_language', as: :edit_language
    match '/company/:id/update_language' => 'companies#update_language', as: :update_language , via: [:put, :post]

  end

  resources :user_sessions

  get 'logout' => 'user_sessions#destroy', :as => :logout
  get 'login' => 'user_sessions#new', :as => :login
  match 'signup(/:registration_key)' => 'user_sessions#signup', :as => :signup, via: [:get, :post, :patch]

  match '/forgot_password' => 'fronts#forgot_password', :as => :forgot_password, via: [:get, :post]
  match '/change_password' => 'fronts#change_password', :as => :change_password, via: [:get, :post, :patch]
  get 'dashboard' => 'fronts#dashboard', :as => :dashboard
  match 'activate/:activation_key' => 'fronts#user_activation', :as => :activation_link, via: [:get]
  match '/profile' => 'fronts#profile', :as => :profile, via: [:get, :post, :patch]
  get '/show_search_box/:toggle/:model/:pm' => 'fronts#show_search_box', :as => :show_search_box
  match 'contact_us' => 'fronts#contact_us', :as => :contact_us, via: [:get, :post, :patch]
  get '/other/:page_id' => 'fronts#other', :as => :other

  # You can have the root of your site routed with "root"
  root 'fronts#dashboard'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :company_admins
  has_many :company_languages
  has_one :payment_type 

  validates :name, :business_id, :url, :contact_person, :contact_email, :presence => true
  validates :name, uniqueness: true
  validates :url, uniqueness: true
  validates_format_of :contact_email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  
  include SearchHandler
  
  mount_uploader :company_logo, ImageUploader
  mount_uploader :company_banner, ImageUploader
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < ApplicationController
  before_filter :get_company_from_params, :only => [:show, :edit, :update, :destroy, :update_company_language, :edit_language,:update_language]
  helper_method :sort_column, :sort_direction
  
  # GET /companise list action
  def index
    session[:search_params] = params[:company] ? params[:company] : nil
    session[:set_pager_number] = params[:set_pager_number] if params[:set_pager_number]

    if session[:set_pager_number].nil?
      session[:set_pager_number] = PER_PAGE
    end
    @companies = Company.all.
        search(session[:search_params]).
        order(sort_column + " " + sort_direction).
        paginate(:per_page => session[:set_pager_number], :page => params[:page])
    @params_arr = ['name']
  end

  # GET /companise/1/edit
  def new
    @company = Company.new
  end

  # POST /companise
  def create
    @company = Company.new(company_params)
    respond_to do |format|
      if @company.save
        format.html { redirect_to admin_companies_url, notice: t("general.successfully_created") }
        format.json { head :no_content }
      else
        format.html { render action: 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # GET /companise/1
  def show
  end

  # GET /companise/1/edit
  def edit
  end
  
  # PATCH/PUT /companise/1
  def update
    respond_to do |format|
      if @company.update_attributes(company_params)
        format.html { redirect_to admin_companies_url, notice: t("general.successfully_updated") }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /companise/1
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to admin_companies_url, notice: t("general.successfully_destroyed") }
    end
  end
  
  def language_list
    @companies = Company.all
    @languages = Language.all
    @params_arr = ['name']
  end

  def edit_language
    @languages = Language.all
  end

  def update_language
    respond_to do |format|
      default_language = Language.find_by_code('en')
      company_languages = @company.company_languages.editable_languages(default_language.id)
      company_languages.update_all activate: false
      if params[:company_language].present?
        params[:company_language].each do |language_id|
          if !(@company.company_languages.pluck(:language_id).include?(language_id.to_i))
            CompanyLanguage.create({company_id: @company.id, language_id: language_id, activate: true})
            format.html { redirect_to admin_companies_url, notice: t("general.successfully_created") }
            format.json { head :no_content }
          else
            company_language  = @company.company_languages.find_by_language_id(language_id)
            if company_language.update_attribute('activate', true)
              format.html { redirect_to admin_language_list_path, notice: t("general.successfully_updated") }
              format.json { head :no_content }
            else
              format.html { render action: 'edit_language' }
              format.json { render json: company_language.errors, status: :unprocessable_entity }
            end
          end
        end
      else
        format.html { redirect_to admin_language_list_path, notice: t("general.successfully_updated") }
        format.json { head :no_content }
      end
    end
  end

  private
  
  def get_company_from_params
    @company  = Company.find(params[:id])
  end
  
  def company_params
    params[:company][:morning_start_time] = params[:morning_stime] + ':' + params[:morning_etime]
    params[:company][:evening_end_time] = params[:evening_stime] + ':' + params[:evening_etime]
    #:name, :business_id, :address, :zip, :city, :contact_person, :contact_email, :sender_email, :contact_phone, :contact_fax, :url, :mob_url, :default_reservation_time, :schedule_time_interval, :weekdays, :release_day, :release_vip_day, :reservation_time_limit, :regular_reservation_limit, :unregular_reservation_limit, :agent_interval, :max_real_length, :real_length_slot, :home_display, :appointment_free, :sort_order, :purpose_length_disp, :c_e_appointment_limit, :week_of_month, :agent_run, :num_tab, :display_tab_name, :logo_link, :logo_image, :company_logo, :company_banner, :secondary_logo_image, :secondary_url, :update_url, :send_email, :send_sms, :forenoon_start, :forenoon_end, :afternoon_start, :afternoon_end, :morning_start_time, :evening_end_time, :close, :appConfirm, :reason_text, :display_receipt, :display_checkin, :is_def_cashReg, :display_reserve_btn, :mail_format, :massmail, :massmail_internal, :appoinment_reservation_day, :address_on_receipt, :toplogo_link, :comlogo_link, :combanner_link, :default_logo_display, :web_id_login, :green_box, :display_cal
    params.require(:company).permit!
  end
  
  def sort_column
    Company.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end

end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
  def is_selected_company_language?(company,language)
    company_languages = company.company_languages.find_by_language_id(language.id)
    if company_languages.present?
      return company_languages.activate
    else
      false
    end
  end
end

app/views/admin/companies/_company_language_form.html.erb
<%= form_for :company_language , url: admin_update_language_path(@company), :html => { :class => 'form-horizontal' } do |f| %>

    <div class="control-group">
      <%= f.label :company_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.label @company.name, :class => 'control-label' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label 'Language', :class => 'control-label' %>
      <div class="controls">
      <%company_languages = @company.company_languages.pluck(:id)%>
      <%@languages.each do |language|%>
            <%= language.name %>
            <%= check_box_tag("company_language[]",language.id,  is_selected_company_language?(@company,language)) %>
      <%end%>
      </div>

    </div>


    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
    </div>

<% end %>

app/views/admin/companies/_fetchAll.html.erb
<%= form_for :company, :url => { :action => 'index' }, :html => { :id => "index_form" }, :method => "get", :remote => true do |f| %>
<table class="table table-striped">
 <thead>
  <tr>
  	<th width="5%"><%= check_box_tag "check_all", "" %><%= t("general.all") %></th>
    <th width="20%"><%= sortable "name", t("name") %></th>
    <th width="20%"><%= sortable "contact_person", t("contact_person") %></th>
    <th width="15%"><%= sortable "url", t("general.url")%></th>
    <th width="15%"><%= sortable "mob_url", t("general.mob_url")%></th>
    <th width="15%"><%= t("general.actions") %></th>
  </tr>
 </thead>

  <tbody>
    <% if @companies.size > 0 %>
      <% @companies.each do |company| %>
        <tr>
          <th><%= check_box_tag "rec["+company.id.to_s+"]", "" %></th>
          <td><%= company.name %></td>
          <td><%= company.contact_person %></td>
          <td><%= company.url %></td>
          <td><%= company.mob_url %></td>
          <td>
			      <%= link_to t('general.edit'),
			                  edit_admin_company_path(company), :class => 'btn btn-mini' %>
			      <%= link_to t('general.destroy'),
			                  admin_company_path(company),
			                  :method => :delete,
			                  :data => { :confirm => t('general.confirm') },
			                  :class => 'btn btn-mini btn-danger' %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr><th colspan="6"><%= t("general.record_not_found") %></th></tr>
    <% end %>
  </tbody>
</table>
<div class="fr">
	<table>
		<tr>
            <td><%= render 'layouts/common_pager' %></td>
			<td>
				<%= select_tag "set_pager_number", options_for_select(get_pager_numbers, session[:set_pager_number]),
																	:data => { :remote => true, :url => url_for(:action => "index") },
																	:class => ""  %>
			</td>
			<td>&nbsp;</td>
			<td>
				<%= will_paginate @companies %>
			</td>
		</tr>
	</table>
</div>
<% end %>

app/views/admin/companies/_form.html.erb
<%= form_for ["admin", @company], :html => { :class => 'form-horizontal', :name => 'new_company'} do |f| %>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %><span class="redStart">*</span>
      <div class="controls">
        <%= f.text_field :name, :class => 'input-xlarge' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :business_id, :class => 'control-label' %><span class="redStart">*</span>
      <div class="controls">
        <%= f.text_field :business_id, :class => 'input-xlarge' %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :address, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :address, :class => 'input-xlarge' %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :zip, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :zip, :class => 'input-xlarge' %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :city, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :city, :class => 'input-xlarge' %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :contact_person, :class => 'control-label' %><span class="redStart">*</span>
      <div class="controls">
        <%= f.text_field :contact_person, :class => 'input-xlarge' %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :contact_email, :class => 'control-label' %><span class="redStart">*</span>
      <div class="controls">
        <%= f.text_field :contact_email, :class => 'input-xlarge' %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :contact_phone, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :contact_phone, :class => 'input-xlarge' %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :contact_fax, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :contact_fax, :class => 'input-xlarge' %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :url, :class => 'control-label' %><span class="redStart">*</span>
      <div class="controls">
        <%= f.text_field :url, :class => 'input-xlarge' %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :mob_url, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :mob_url, :class => 'input-xlarge' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :logo_link, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :logo_link, :class => 'input-xlarge' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :url, :class => 'control-label' %>
      <div class="controls">
        <%= f.file_field :company_logo, :class => 'input-xlarge' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :company_banner, :class => 'control-label' %>
      <div class="controls">
        <%= f.file_field :company_banner, :class => 'input-xlarge' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :default_reservation_time, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :default_reservation_time, :class => 'input-xlarge' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :schedule_time_interval, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :schedule_time_interval, :onblur => "makeCombo();", :class => 'input-xlarge' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :num_tab, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :num_tab, :class => 'input-xlarge' %>
      </div>
    </div>  
    
    <div class="control-group">
      <%= f.label :morning_start_time, :class => 'control-label' %>
      <div class="controls">
        <%= select_tag "morning_stime", options_for_select(get_time(1, 23), @company.morning_start_time.present? ? @company.morning_start_time.split(':')[0]: '08'), :class => "input-xlarge" %>
        <%= select_tag "morning_etime", options_for_select(get_time(1, 45), @company.morning_start_time.present? ? @company.morning_start_time.split(':')[1]: '00'), :class => 'input-xlarge' %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :evening_end_time, :class => 'control-label' %>
      <div class="controls">
        <%= select_tag "evening_stime", options_for_select(get_time(1, 23), @company.evening_end_time.present? ? @company.evening_end_time.split(':')[0]: '08'), :class => "input-xlarge" %>
        <%= select_tag "evening_etime", options_for_select(get_time(1, 45), @company.evening_end_time.present? ? @company.evening_end_time.split(':')[1]: '00'), :class => 'input-xlarge' %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :send_email, :class => 'control-label' %>
      <div class="controls">
        <%= check_box_tag 'company[send_email]', 1, @company.send_email %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :num_tab, :class => 'control-label' %>
      <div class="controls">
        <%= f.radio_button :mail_format, 'html' %>Html &nbsp; 
        <%= f.radio_button :mail_format, 'text' %>Text
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :display_receipt, :class => 'control-label' %>
      <div class="controls">
        <%= check_box_tag 'company[display_receipt]', 1, @company.display_receipt %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :send_sms, :class => 'control-label' %>
      <div class="controls">
        <%= check_box_tag 'company[send_sms]', 1, @company.send_sms %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :appConfirm, :class => 'control-label' %>
      <div class="controls">
        <%= check_box_tag 'company[appConfirm]', 1, @company.appConfirm %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :display_checkin, :class => 'control-label' %>
      <div class="controls">
        <%= check_box_tag 'company[display_checkin]', 1, @company.display_checkin %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :close, :class => 'control-label' %>
      <div class="controls">
        <%= check_box_tag 'company[close]', 1, @company.close %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :reason_text, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :reason_text, :class => 'input-xlarge' %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :massmail, :class => 'control-label' %>
      <div class="controls">
        <%= f.radio_button :massmail, '1' %>Enable &nbsp; <%= f.radio_button :massmail, '0' %>Disable
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :massmail_internal, :class => 'control-label' %>
      <div class="controls">
        <%= f.radio_button :massmail_internal, '1' %>Enable &nbsp; <%= f.radio_button :massmail_internal, '0' %>Disable
      </div>
    </div>

    
    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', admin_companies_path, :class => 'btn' %>
    </div>

<% end %>

app/views/admin/companies/_languages.html.erb
<%= form_for :company, :url => { :action => 'index' }, :html => { :id => "index_form" }, :method => "get", :remote => true do |f| %>
    <table class="table table-striped">
      <thead>
      <tr>
        <th width="20%"><%= t("company_name") %></th>
        <th width="20%"><%= t("language_name") %></th>
        <th width="15%"><%=t("activate")%></th>
        <th width="15%"><%= t("general.actions") %></th>
      </tr>
      </thead>

      <tbody>
      <% if @companies.size > 0 %>
          <% @companies.each do |company| %>
              <tr>
                <td>
                  <%= company.name %>
                </td>
                  <td>
                    <%@languages.each do |language|%>
                        <%=language.name%>
                        </br>
                    <%end%>
                  </td>
                <td>
                  <%@languages.each do |language|%>
                      <%= (is_selected_company_language?(company,language))? 'Yes': 'No' %>
                      <br>
                  <%end%>
                </td>
                <td>
                  <%= link_to t('general.edit'),
                              admin_edit_language_path(company), :class => 'btn btn-mini' %>
                </td>

            </tr>
          <% end %>
      <% else %>
          <tr><th colspan="6"><%= t("general.record_not_found") %></th></tr>
      <% end %>
      </tbody>
    </table>
    <div class="fr">
      <table>
        <tr>
          <td><%= render 'layouts/common_pager' %></td>
          <td>
            <%= select_tag "set_pager_number", options_for_select(get_pager_numbers, session[:set_pager_number]),
                           :data => { :remote => true, :url => url_for(:action => "index") },
                           :class => ""  %>
          </td>
          <td>&nbsp;</td>
          <td>
            <%#= will_paginate @companies %>
          </td>
        </tr>
      </table>
    </div>
<% end %>

app/views/admin/companies/edit.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h4><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h4>
</div>
<%= render :partial => 'form' %>

app/views/admin/companies/edit_language.html.erb
<%- model_class = CompanyLanguage -%>
<div class="page-header">
  <h4><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h4>
</div>
<%= render :partial => 'company_language_form' %>

app/views/admin/companies/index.html.erb
<%- model_class = Company -%>

<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<div class="page-header">
  <h4><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %> (<span id="count_records"><%= @companies.count %></span>)
	<div class="searchRight fr">
		<%= link_to t("general.search"), show_search_box_path("true", model_class, @params_arr.join(',')), :remote => true, :class => 'btn btn-primary btn-small' %>&nbsp;

		<%= link_to t('general.add'),
		            new_admin_company_path,
		            :class => 'btn btn-primary btn-small' %>

    <%= link_to t('general.destroy'), "#destroy_all", :id => "destroy_all", :class => 'btn btn-primary btn-small btn-danger' %>
	</div>
	</h4>
</div>


<div id="div_update_search">
	<% if session[:search_params] %>
		<% params[:model] = controller_name.classify %>
		<%= render "fronts/search" %>
	<% end %>
</div>

<div id="div_update">
	<%= render "fetchAll" %>
</div>

app/views/admin/companies/index.js.erb
$("#div_update").html("<%= escape_javascript(render("fetchAll")) %>");
$("#count_records").html("<%= @companies.count %>");
$("#spinner").hide();

$('#check_all').click (function() {
  $(this).closest('table').find('input[type=checkbox]').prop('checked', this.checked);
});

$('.pagination a').attr('data-remote', 'true');

app/views/admin/companies/language_list.html.erb
<%- model_class = CompanyLanguage -%>

<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<div class="page-header">
  <h4><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %> (<span id="count_records"><%= @companies.count %></span>)
    <div class="searchRight fr">
      <%= link_to t("general.search"), show_search_box_path("true", model_class, @params_arr.join(',')), :remote => true, :class => 'btn btn-primary btn-small' %>&nbsp;

      <%#= link_to t('general.add'),
                  new_admin_company_path,
                  :class => 'btn btn-primary btn-small' %>

      <%#= link_to t('general.destroy'), "#destroy_all", :id => "destroy_all", :class => 'btn btn-primary btn-small btn-danger' %>
    </div>
  </h4>
</div>


<div id="div_update_search">
  <% if session[:search_params] %>
      <% params[:model] = controller_name.classify %>
      <%= render "fronts/search" %>
  <% end %>
</div>

<div id="div_update">
  <%= render "languages" %>
</div>

app/views/admin/companies/new.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h4><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>
</div>

<% if @company.errors.any? %>
  <div id="errorExplanation">
    <ul>
    <% @company.errors.full_messages.each do |msg| %>
      <li><span class="text-error text-message"><%= msg %></span></li>
    <% end %>
    </ul>
  </div>
  <% end %>

<%= render :partial => 'form' %>

app/views/admin/companies/show.html.erb
<h1>Companies#show</h1>
<p>Find me in app/views/companies/show.html.erb</p>